[project]
name = "ssl-probe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lightning>=2.6.5",
    "opensmile>=2.6.0",
    "quick-convert",
    "scikit-learn>=1.9.0",
    "scipy>=1.17.1",
    "torchmetrics>=1.9.0",
    "transformers>=5.14.1",
    "wandb>=0.28.1",
]

[tool.uv.sources]
quick-convert = { path = "../quick-convert", editable = true }
